version: "3.3"
services:
  node:
    container_name: 'node-local'
    stdin_open: true
    tty: true
    image: node:18
    working_dir: /www/pdf/pdf-frontend
    user: node
    volumes:
      - ..:/www
    ports:
      - "9499:9499"
    networks:
      - node-net

  proxy:
    restart: always
    image: jwilder/nginx-proxy
    volumes:
      - .:/var/www/pdf
      - ./proxy/hosts:/etc/hosts
      - /var/run/docker.sock:/tmp/docker.sock
      - ./proxy/my_nginx.conf:/etc/nginx/conf.d/my_nginx.conf
    ports:
      - "80:81"
    networks:
      - pdf-net
    depends_on:
      - backend

  backend:
    restart: always
    build: .
    volumes:
      - ..:/www/src
    command: ./pdf
    working_dir: /www/src/pdf
    networks:
      - pdf-net

networks:
  pdf-net:
    driver: bridge
  node-net:
    driver: bridge